"use client";
import { useState } from "react";
import { Plus, Minus } from "lucide-react";

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  const faqs = [
    {
      question: "Is content created by Abun original?",
      answer:
        "Yes, content created by Abun is original. The technology used by Abun generates unique, high-quality articles by analyzing top-ranking content and SEO best practices. It ensures that the content is well-researched for the keyword making it valuable and relevant to the target audience. The tool avoids producing “robotic” or “GPT-like” content, focusing instead on creating human-like, engaging articles that adhere to E.E.A.T. standards (Experience, Expertise, Authoritativeness, Trustworthiness). This approach ensures that the content is not only original but also effective in driving organic traffic and ranking higher on search engines.",
    },
    {
      question: "Does Abun require technical expertise to use?",
      answer: `Not at all. We have designed Abun with user-friendliness in mind. You don’t need extensive technical knowledge to benefit from our automation features. Publish articles in 4 simple steps:
1. Find Keywords 
2. Choose Keywords to Write Articles for 
3. Choose Relevant Titles 
4. Publish Articles Instantly.`,
    },
    {
      question: "Is the generated content optimized for SEO? How does it contribute to attracting organic traffic?",
      answer:
        "Absolutely! Our Abun content generator AI is made to follow the best SEO practices needed for your blog or article to show up on search engine results. We dig deep into relevant keywords for your target audience. Everything from the blog content to the title, heading tags, metadata, images, and readability score is optimized to make sure more people find your content through search engines. This helps bring organic traffic to your website.",
    },
    {
      question: "Does Google rank AI-written content? Will I get penalized by google for Abun's content?",
      answer:
        "Whether the content is created using AI or written by humans, Google ranks articles based on the quality of the content. Articles created using Abun also feature media-rich content, including images and a featured thumbnail. https://developers.google.com/search/blog/2023/02/google-search-and-ai-content",
    },
    {
      question: "How is Abun better than ChatGPT & other alternatives?",
      answer:
        "Abun offers several advantages over ChatGPT and other alternatives, particularly in the context of automated content creation and SEO optimization. While ChatGPT is a versatile AI model capable of generating text, Abun is specifically designed for SEO-optimized content creation. It excels in generating articles that rank well on search engines by using advanced algorithms to analyze SERP data, identify winning article types, and incorporate relevant keywords with real volume statistics.",
    },
    {
      question: "What is the length of Abun's articles?",
      answer:
        "The articles created by Abun are based on the keyword & the title which the article is generated. Some topics can be simple like “How to wash hands?”, while other topics can be complex like “How to install ubuntu on your system?”. Depending on all these factors our system determines the ideal length for the generated article. The generated article length is between 1500-7500 words.",
    },
    {
      question: "What is the process for keyword research? How does it differ from other AI tools?",
      answer:
        "Our AI-driven keyword research process uses advanced algorithms to identify new and relevant keywords within your niche. It provides real keyword volume statistics to back up suggestions, helping you target the most effective keywords. Unlike other tools, Abun can also analyze competitor keywords, allowing you to uncover opportunities and gaps in the market.",
    },
    {
      question: `What makes the content generated by Abun different from "robotic" or "GPT-like" content?`,
      answer: `Unlike generic AI-generated content, Abun produces human-like, valuable content tailored to the end reader. It ensures that all articles are well-researched, incorporating data and insights that align with E.E.A.T. standards (Experience, Expertise, Authoritativeness, Trustworthiness). This approach guarantees content that is both informative and engaging, reducing the risk of the content appearing robotic or fabricated.`,
    },
    {
      question: "How does the tool analyze SERP-winning content? what factors does it consider for ranking?",
      answer:
        "Abun analyzes SERP-winning content by examining factors like keyword usage, content structure, article length, and the presence of engaging elements like images, tables, and lists. It identifies common themes and topics covered by top-ranking articles and incorporates these insights into the content it generates. This analysis helps ensure that your articles include the necessary components to perform well in search engine rankings.",
    },
    {
      question: "Which CMS do you support for auto-posting articles using Abun?",
      answer:
        "Currently we are supporting WordPress, Webflow, Wix, & Shopify integrations for auto-posting articles on your blog. If you are not using any of these platforms, you can download the article as an HTML or Markdown format or copy-paste it into your blogging CMS.",
    },
    {
      question: "How does blog \"Content Automation\" function?",
    answer:
    "To automate your blog posting, link your CMS with the Abun platform. You can begin by setting up an automation project by selecting a keyword project that targets a list of relevant keywords. The tool is configured to generate and submit a specified number of articles to the chosen CMS platform. This direct publishing feature eliminates manual uploading. You have the flexibility to publish at any time of the day, ensuring content aligns with your strategic release schedule. Additionally, the flexibility to use only the generated articles for auto-posting ensures consistency in quality and style.",
    },
    {
      question: "Can Abun generate content in multiple languages?",
      answer:
        "Yes, Abun can generate content in 50+ languages. Abun can help you reach a wider audience by creating articles for different linguistic markets. Abun’s multilingual capabilities make it a valuable tool for businesses looking to expand their content strategy beyond a single language.",
    },
    {
      question: "Do you have a free plan to use Abun?",
      answer:
        "Yes, we offer a free plan for users to experience its features firsthand. It’s a great opportunity to explore how Abun automation can revolutionize your content creation and SEO efforts. Signup for the Free Plan now!",
    },

  ];

  const toggleFAQ = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section className="w-full flex flex-col items-center text-left py-15 xl:py-20 md:py-20 sm:py-15 px-3 bg-[linear-gradient(180deg,_#F1F1F9_37%,_#FFFFFF_100%)] md:px-5">
      {/* Section Title */}
      <div className="w-full max-w-[1200px]">
        <h2 className="pt-10 pb-10 text-[48px] text-black font-bold leading-[1.1em]">
          Questions? We have Answers
        </h2>
      </div>

      {/* FAQ List */}
      <div className="w-full max-w-[1200px] border-b border-[#B1B6BE]">
        {faqs.map((faq, index) => (
          <div
            key={index}
            onClick={() => toggleFAQ(index)}
            className={`flex flex-col cursor-pointer ${
              index !== 0 ? "border-t border-[#B1B6BE]" : ""
            }`}
          >
            {/* Question */}
            <div
              className={`flex items-center gap-4 py-5 px-3 transition-colors duration-300 hover:bg-white ${
                openIndex === index ? "bg-white" : ""
              }`}
            >
              <button className="text-black">
                {openIndex === index ? <Minus size={22} /> : <Plus size={22} />}
              </button>
              <div className="text-[20px] text-black font-bold">{faq.question}</div>
            </div>

            {/* Smooth Animated Answer (expands downward only) */}
            <div
              className={`grid transition-all duration-500 ease-in-out ${
                openIndex === index
                  ? "grid-rows-[1fr] opacity-100 py-2"
                  : "grid-rows-[0fr] opacity-0 py-0"
              }`}
            >
              <div className="overflow-hidden">
                <p className="p-4 mt-[-5px] pb-10 mb-8 text-black border-solid border-[#eee] border-[1px] text-[18px] leading-[1.6em] leading-relaxed">
                  {faq.answer}
                </p>
              </div>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
}
